# Generated by Django 5.1.6 on 2025-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Adhar',
            new_name='Aadhar',
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='abcd@gmail.com', max_length=254),
        ),
    ]
