# Generated by Django 5.1.6 on 2025-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_adhar_account_aadhar_alter_account_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Account_number',
            field=models.BigAutoField(default=1234567890, primary_key=True, serialize=False, unique=True),
        ),
    ]
