# Generated by Django 5.1.6 on 2025-04-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Account_number',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
