# Generated by Django 5.1.6 on 2025-04-11 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_otp_alter_account_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Account_number',
            new_name='Acc',
        ),
    ]
