# Generated by Django 5.1.6 on 2025-04-11 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_account_number_account_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Acc',
            new_name='acc',
        ),
    ]
