# Generated by Django 5.1.6 on 2025-04-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_acc_account_acc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='otp',
            new_name='OTP',
        ),
    ]
